// rcf+tab for autogenerated function 
import React from 'react'
import { Link } from 'react-router-dom'
export default function Header() {
    return (
        <header style={headerStyle}>
            <h1>Todo List</h1>
            <Link style={linkStyle} to="/">Home</Link> | <Link style={linkStyle} to="/About">About</Link>
        </header>
    )
}
const headerStyle = {
    backgroundColor: "#333",
    textAlign: "center",
    padding: "10px",
    color: "#fff"
}
const linkStyle = {
    color: "#fff",
    textDecoration: "none"
}